### ISSUE TITLE
Move Java samples into polyglot-maven-examples

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#155]
From https://github.com/takari/polyglot-maven/tree/master/polyglot-java/samples 
to github.com/takari/polyglot-maven-examples

**Comment by mosabua** [comment]
Wanna take that on @sveryovka

**Comment by sveryovka** [comment]
https://github.com/takari/polyglot-maven-examples/pull/8

**Comment by mosabua** [comment]
Thanks for the PR and changes.

**Comment by mosabua** [comment]
The examples project build does not work with 0.3.1-SNAPSHOT in master. Can you check?

**Comment by sveryovka** [comment]
Just checked this and it works fine for me. Please post error message you get.

**Comment by mosabua** [comment]
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:1: error: package org.sonatype.maven.polyglot.java.dsl does not exist
public class POMab893fd387944e809024318d853edcd7 extends org.sonatype.maven.polyglot.java.dsl.ModelFactory {
                                                                                             ^
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:6: error: cannot find symbol
                modelVersion = "4.0.0";
                ^
  symbol:   variable modelVersion
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:7: error: cannot find symbol
                groupId = "org.sample1";
                ^
  symbol:   variable groupId
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:8: error: cannot find symbol
                artifactId = "project1";
                ^
  symbol:   variable artifactId
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:9: error: cannot find symbol
                packaging = "jar";
                ^
  symbol:   variable packaging
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:10: error: cannot find symbol
                version = "1.0-SNAPSHOT";
                ^
  symbol:   variable version
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:13: error: cannot find symbol
                        property(name1 -> "property_1"),
                        ^
  symbol:   method property((name1)->"[...]ty_1")
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:14: error: cannot find symbol
                        property(name2 -> "property_2")
                        ^
  symbol:   method property((name2)->"[...]ty_2")
  location: class POMab893fd387944e809024318d853edcd7
/tmp/1521734087947-0/POMab893fd387944e809024318d853edcd7.java:18: error: cannot find symbol
                        dependency(groupId -> "junit", artifactId -> "junit", version -> "3.8.1", scope -> "test")
                        ^
  symbol:   method dependency((groupId)->"junit",(artifactI[...]unit",(version)->"3.8.1",(scope)->"test")
  location: class POMab893fd387944e809024318d853edcd7
9 errors
[ERROR] Failed to dynamically load class POMab893fd387944e809024318d853edcd7
java.lang.ClassNotFoundException: POMab893fd387944e809024318d853edcd7
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at java.lang.Class.forName0 (Native Method)
    at java.lang.Class.forName (Class.java:348)
    at org.sonatype.maven.polyglot.java.JavaModelReader.compileJavaCode (JavaModelReader.java:126)
    at org.sonatype.maven.polyglot.java.JavaModelReader.read (JavaModelReader.java:145)
    at org.sonatype.maven.polyglot.io.ModelReaderSupport.read (ModelReaderSupport.java:48)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read (TeslaModelProcessor.java:114)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read (TeslaModelProcessor.java:95)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel (DefaultModelBuilder.java:536)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:276)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:432)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:400)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:362)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:397)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:388)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:81)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.NullPointerException
    at org.apache.maven.model.io.xpp3.MavenXpp3Writer.write (MavenXpp3Writer.java:114)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read (TeslaModelProcessor.java:118)
    at org.sonatype.maven.polyglot.TeslaModelProcessor.read (TeslaModelProcessor.java:95)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel (DefaultModelBuilder.java:536)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:276)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:432)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:400)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:362)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:397)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:388)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:81)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by sveryovka** [comment]
I still can't reproduce this. To troubleshoot this is can you please run maven with "-X" option (e.g. mvn clean package -X) and in the output find wollowing lines:
````
[DEBUG] Replaced class name to be POM877dd6b00bd54f95a51acbffae9328ab full src =public class POM877dd6b00bd54f95a51acbffae9328ab extends org.sonatype.maven.polyglot.java.dsl.ModelFactory {

        @SuppressWarnings({ "unchecked" })
        public void project() {

                modelVersion = "4.0.0";
                groupId = "org.sample1";
                artifactId = "project1";
                packaging = "jar";
                version = "1.0-SNAPSHOT";

                properties(
                        property(name1 -> "property_1"),
                        property(name2 -> "property_2")
                );

                dependencies(
                        dependency(groupId -> "junit", artifactId -> "junit", version -> "3.8.1", scope -> "test")
                );

        }
}

[DEBUG] Created temp fileC:\Users\sveryov\AppData\Local\Temp\1521812769057-0/POM877dd6b00bd54f95a51acbffae9328ab.java to compile POM.java
[DEBUG] Calculated classpath for dynamic POM.java compilation as /C:/java/apache-maven-3.5.2/lib/commons-lang3-3.5.jar;/C:/java/apache-maven-3.5.2/lib/maven-model-3.5.2.jar;/C:/java/apache-maven-3.5.2/lib/plexus-utils-3.1.0.jar;/D:/java_work/MVN_REPO/io/takari/polyglot/polyglot-java/0.3.1-SNAPSHOT/polyglot-java-0.3.1-SNAPSHOT.jar;/D:/java_work/MVN_REPO/io/takari/polyglot/polyglot-common/0.3.1-SNAPSHOT/polyglot-common-0.3.1-SNAPSHOT.jar;/D:/java_work/MVN_REPO/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar;/D:/java_work/MVN_REPO/commons-logging/commons-logging/1.2/commons-logging-1.2.jar;/D:/java_work/MVN_REPO/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
[DEBUG] Dynamically compiled class C:\Users\sveryov\AppData\Local\Temp\1521812769057-0/POM877dd6b00bd54f95a51acbffae9328ab.java
[DEBUG] Added URL file:/C:/Users/sveryov/AppData/Local/Temp/1521812769057-0/ to Maven class loader to load class dynamically
[DEBUG] Extension realms for project org.sample1:project1:jar:1.0-SNAPSHOT: (none)
````

Interesting part here is ````Calculated classpath for dynamic POM.java```` Line before you will see path to actual Java class to be compiled. In my example this is ````C:\Users\sveryov\AppData\Local\Temp\1521812769057-0/POM877dd6b00bd54f95a51acbffae9328ab.java````. And please try compiling this java class manually (using javac) with class path you get from debug output.

**Comment by sveryovka** [comment]
I am currently looking at the issue. Will update with status later

**Comment by sveryovka** [comment]
Should be fixed now. You need to pull latest changes. This issue was Linux specific.
